version: '3'
services:
  backend:
    build:
      context: ./takehome_app/backend
      dockerfile: Dockerfile
    image: backend-image
    ports:
      - "5432:5432" # Change the port mapping here
    # networks:
    #   backend_network:
    #     ipv4_address: 172.28.2.2

  frontend:
    build:
      context: ./takehome_app/frontend
      dockerfile: Dockerfile
    image: frontend-image
    ports:
      - "3000:3000"
  
# networks:
#   backend_network:
#     ipam:
#       driver: default
#       config:
#       - subnet: 172.28.0.0/24