version: '3'
services:
  backend:
    build:
      context: ./takehome_app/backend
      dockerfile: Dockerfile
    image: backend-image
    ports:
      - "5432:5432" 
    

  frontend:
    build:
      context: ./takehome_app/frontend
      dockerfile: Dockerfile
    image: frontend-image
    ports:
      - "3000:3000"
  